export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

export const USER_ADD = 'USER_ADD';
export const USER_GET = 'USER_GET';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_DELETE = 'USER_DELETE';

export const ACTIVITY_ADD = 'ACTIVITY_ADD';
export const ACTIVITY_TOGGLE_ATTEND = 'ACTIVITY_TOGGLE_ATTEND';
export const ACTIVITY_UPDATE = 'ACTIVITY_UPDATE';
export const ACTIVITY_DELETE = 'ACTIVITY_DELETE';

export const CATEGORY_GET = 'CATEGORY_GET';
export const CATEGORY_SET_CHECKED = 'CATEGORY_SET_CHECKED';
export const WHEN_SET_CHECKED = 'WHEN_SET_CHECKED';
export const ATTENDEES_SET_RANGE = 'ATTENDEES_SET_RANGE';

export const RESET = 'RESET';
