const AUTH_LOGIN = 'AUTH_LOGIN';
const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
const AUTH_LOGOUT = 'AUTH_LOGOUT';
const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

const USER_ADD = 'USER_ADD';
const USER_GET = 'USER_GET';
const USER_UPDATE = 'USER_UPDATE';
const USER_DELETE = 'USER_DELETE';

const ACTIVITY_ADD = 'ACTIVITY_ADD';
const ACTIVITY_TOGGLE_ATTEND = 'ACTIVITY_TOGGLE_ATTEND';
const ACTIVITY_UPDATE = 'ACTIVITY_UPDATE';
const ACTIVITY_DELETE = 'ACTIVITY_DELETE';

const CATEGORY_GET = 'CATEGORY_GET';
const CATEGORY_SET_CHECKED = 'CATEGORY_SET_CHECKED';
const WHEN_SET_CHECKED = 'WHEN_SET_CHECKED';
const ATTENDEES_SET_RANGE = 'ATTENDEES_SET_RANGE';

const RESET = 'RESET';
// to avoid using export keyword too many time better do this
export {
  AUTH_LOGIN,
  AUTH_LOGIN_SUCCESS,
  AUTH_LOGIN_ERROR,
  AUTH_LOGOUT,
  AUTH_SET_TOKEN,
  USER_ADD,
  USER_GET,
  USER_UPDATE,
  USER_DELETE,
  ACTIVITY_ADD,
  ACTIVITY_TOGGLE_ATTEND,
  ACTIVITY_UPDATE,
  ACTIVITY_DELETE,
  CATEGORY_GET,
  CATEGORY_SET_CHECKED,
  WHEN_SET_CHECKED,
  ATTENDEES_SET_RANGE,
  RESET,
}
