export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const USER_ADD = 'USER_ADD';

export const ACTIVITY_ADD = 'ACTIVITY_ADD';
export const ACTIVITY_TOGGLE_ATTEND = 'ACTIVITY_TOGGLE_ATTEND';
export const ACTIVITY_FETCH_SUCCESS = 'ACTIVITY_FETCH_SUCCESS';

export const CATEGORY_SET_CHECKED = 'CATEGORY_SET_CHECKED';
export const WHEN_SET_CHECKED = 'WHEN_SET_CHECKED';
export const ATTENDEES_SET_RANGE = 'ATTENDEES_SET_RANGE';

export const RESET = 'RESET';
